# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1 on 2026-08-09 18:39

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_pricefighter", "0001_initial"),
        ("django_pricefighter", "0002_quoteconfig_pricingrule"),
        ("django_pricefighter", "0003_pricedecision"),
    ]

    dependencies = [
        # Cross-app dep pinned to the squash itself, not its leaf — an existing database
        # that ran the historical regional chain records the squash name, and a leaf-dep
        # would raise InconsistentMigrationHistory on upgrade.
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(max_length=3)),
                ("range_from", models.DecimalField(decimal_places=2, max_digits=10)),
                ("range_to", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("band_dn", models.DecimalField(decimal_places=2, max_digits=10)),
                ("band_up", models.DecimalField(decimal_places=2, max_digits=10)),
                ("undercut", models.DecimalField(decimal_places=2, max_digits=10)),
                ("headroom", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_step", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rounding",
                    models.CharField(
                        choices=[("none", "None"), (".99", ".99"), (".95", ".95"), ("int", "Integer")],
                        default="none",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Config",
                "verbose_name_plural": "Quote Configs",
                "ordering": ["currency", "range_from"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricefighter_default_channels",
                        to="django_regional.language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, related_name="pricefighter_channels", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_pricefighter.channel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Representations",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="PriceDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=2)),
                ("currency", models.CharField(max_length=3)),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("compete", "Compete"),
                            ("raise", "Raise"),
                            ("revert_baseline", "Revert to baseline"),
                            ("hold_at_floor", "Hold at floor (price war)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mode", models.CharField(max_length=20)),
                ("reason", models.JSONField(default=dict)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_decisions",
                        to="django_pricefighter.channel",
                    ),
                ),
                (
                    "representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_decisions",
                        to="django_pricefighter.productrepresentation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[("hold", "Hold"), ("compete", "Compete"), ("raise", "Raise")],
                        default="hold",
                        max_length=10,
                    ),
                ),
                ("price_war", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[("suggestion", "Suggestion"), ("authoritative", "Authoritative")],
                        default="suggestion",
                        max_length=20,
                    ),
                ),
                ("sku", models.CharField(blank=True, default=None, max_length=128, null=True)),
                ("category_idx", models.CharField(blank=True, default=None, max_length=128, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="django_pricefighter.channel",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("sku__isnull", False), ("category_idx__isnull", True), ("channel__isnull", True)),
                            models.Q(("sku__isnull", True), ("category_idx__isnull", False), ("channel__isnull", True)),
                            models.Q(("sku__isnull", True), ("category_idx__isnull", True), ("channel__isnull", False)),
                            _connector="OR",
                        ),
                        name="pricefighter_pricingrule_exactly_one_scope",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productrepresentation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                models.F("channel"),
                name="pricefighter_pr_sku_unique_in_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="pricedecision",
            index=models.Index(fields=["representation"], name="django_pric_represe_2464a7_idx"),
        ),
        migrations.AddIndex(
            model_name="pricedecision",
            index=models.Index(fields=["created_at"], name="django_pric_created_e8dabf_idx"),
        ),
        migrations.AddIndex(
            model_name="pricedecision",
            index=models.Index(fields=["channel", "country", "currency"], name="django_pric_channel_b45977_idx"),
        ),
    ]
